version: "3"

volumes:
  mysql-data:

services:

  web:
    image: "nginx:stable-alpine"
    ports:
        - "80:80"
    depends_on:
      - "php"
      - "mysql"
    volumes:
      - "./docker/web/default.conf:/etc/nginx/conf.d/default.conf"
      - ".:/var/www/html"
    
  php:
    build: "./docker/php"
    volumes:
      - "./src:/var/www/html"
    depends_on:
      - "mysql"

  mysql:
    image: "mysql:5.7"
    container_name: "mysql"
    command: "mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci"
    restart: "always"
    env_file: 
      - "./.mysql.env"
    ports:
      - "13306:3306"
    volumes:
      - "mysql-data:/var/lib/mysql"
